### ISSUE TITLE
LES CHAINES LOCALE ET REGIONALE

### ISSUE THREAD

**Issue by ARAB-IPTV** [LeBazarDeBryan/XTVZ_#1]
BONJOUR .
EST CE QUE POSSIBLE D'AJOUTER DES CHAINE LOCALE ET REGIONALE EN LANGUE FRANCAISE / FRANCE BELGE SUISSE / ET MERCI BIEN POUR VOTRE TRAVAIL

**Comment by ARAB-IPTV** [comment]
Alsace 20 | StrasbourgMulhouse
Angers télé | Angers
BFM Azur | Nice – Menton - Cannes – Grasse – Saint Raphaël - Mercantour
BDM TV | Région parisienne (temps partiel)
BFM Paris | Île-de-France
Bip TV | Issoudun - Argenton-sur-Creuse
Canal 32 | Troyes
BFM DICI | GapDigne-les-Bains – Serres – SisteronChâteau-Arnoux
Demain ! IDF | Région parisienne (temps partiel)
BFM Grand Lille | Lille (R15)
BFM Grand Littoral | Boulogne-sur-Mer - Dunkerque
IDF1 | Région parisienne
LCN La Chaîne Normande | Rouen - Neufchâtel-en-Bray
LDV TV | Monistrol-sur-Loire
LMty Sarthe | Le Mans
viàMATÉLÉ | Saint-Quentin - Hirson
viàMoselle TV | Metz - Verdun - Forbach - Longwy - Sarrebourg
Télénantes | Nantes
BFM Marseille | Marseille
Tébéo | Brest
Tébésud | Lorient - Vannes
Télé Bocal | Région parisienne (temps partiel)
TéléGrenoble | Grenoble - Voiron
TL7, Télévision Loire 7 | Saint-Etienne
Télévision Locale du Choletais | Cholet - La Roche-sur-Yon - Nantes
BFM Lyon Métropole | LyonVillefranche-sur-Saône – Lyon – Vienne
TVR | Rennes
ViàTélé Paese | Calvi – L’Île RousseCorte
TV Tours Val-de-Loire | Tours - Blois
TV Vendée
TV7 Bordeaux | Bordeaux - Arcacho
TV8 Mont-Blanc | Savoie et Haute-Savoie
TVPI | Bayonne
BFM Var | Toulon - Hyères
Museum TV Paris | Région parisienne
vià Occitanie Montpellier | Montpellier
vià Occitanie Pays catalan | Perpignan
vià Occitanie Pays gardois | NîmesAlès
vià Occitanie Toulouse | Toulouse
Vosges Télévision | Epinal - Vittel
Wéo Picardie | Abbeville - Amiens
Wéo Nord-Pas de Calais | Lille

**Comment by LeBazarDeBryan** [comment]
> 
> 
> Alsace 20 | StrasbourgMulhouse
> Angers télé | Angers
> BFM Azur | Nice – Menton - Cannes – Grasse – Saint Raphaël - Mercantour
> BDM TV | Région parisienne (temps partiel)
> BFM Paris | Île-de-France
> Bip TV | Issoudun - Argenton-sur-Creuse
> Canal 32 | Troyes
> BFM DICI | GapDigne-les-Bains – Serres – SisteronChâteau-Arnoux
> Demain ! IDF | Région parisienne (temps partiel)
> BFM Grand Lille | Lille (R15)
> BFM Grand Littoral | Boulogne-sur-Mer - Dunkerque
> IDF1 | Région parisienne
> LCN La Chaîne Normande | Rouen - Neufchâtel-en-Bray
> LDV TV | Monistrol-sur-Loire
> LMty Sarthe | Le Mans
> viàMATÉLÉ | Saint-Quentin - Hirson
> viàMoselle TV | Metz - Verdun - Forbach - Longwy - Sarrebourg
> Télénantes | Nantes
> BFM Marseille | Marseille
> Tébéo | Brest
> Tébésud | Lorient - Vannes
> Télé Bocal | Région parisienne (temps partiel)
> TéléGrenoble | Grenoble - Voiron
> TL7, Télévision Loire 7 | Saint-Etienne
> Télévision Locale du Choletais | Cholet - La Roche-sur-Yon - Nantes
> BFM Lyon Métropole | LyonVillefranche-sur-Saône – Lyon – Vienne
> TVR | Rennes
> ViàTélé Paese | Calvi – L’Île RousseCorte
> TV Tours Val-de-Loire | Tours - Blois
> TV Vendée
> TV7 Bordeaux | Bordeaux - Arcacho
> TV8 Mont-Blanc | Savoie et Haute-Savoie
> TVPI | Bayonne
> BFM Var | Toulon - Hyères
> Museum TV Paris | Région parisienne
> vià Occitanie Montpellier | Montpellier
> vià Occitanie Pays catalan | Perpignan
> vià Occitanie Pays gardois | NîmesAlès
> vià Occitanie Toulouse | Toulouse
> Vosges Télévision | Epinal - Vittel
> Wéo Picardie | Abbeville - Amiens
> Wéo Nord-Pas de Calais | Lille
> 
> 
> 

Bonjour, je vous remercie de m'avoir mis la liste des chaîne, j'ajouterai une liste m3u et je la remplirai cette semaine.

**Comment by ARAB-IPTV** [comment]
> > Alsace 20 | StrasbourgMulhouse
> > Angers télé | Angers
> > BFM Azur | Nice – Menton - Cannes – Grasse – Saint Raphaël - Mercantour
> > BDM TV | Région parisienne (temps partiel)
> > BFM Paris | Île-de-France
> > Bip TV | Issoudun - Argenton-sur-Creuse
> > Canal 32 | Troyes
> > BFM DICI | GapDigne-les-Bains – Serres – SisteronChâteau-Arnoux
> > Demain ! IDF | Région parisienne (temps partiel)
> > BFM Grand Lille | Lille (R15)
> > BFM Grand Littoral | Boulogne-sur-Mer - Dunkerque
> > IDF1 | Région parisienne
> > LCN La Chaîne Normande | Rouen - Neufchâtel-en-Bray
> > LDV TV | Monistrol-sur-Loire
> > LMty Sarthe | Le Mans
> > viàMATÉLÉ | Saint-Quentin - Hirson
> > viàMoselle TV | Metz - Verdun - Forbach - Longwy - Sarrebourg
> > Télénantes | Nantes
> > BFM Marseille | Marseille
> > Tébéo | Brest
> > Tébésud | Lorient - Vannes
> > Télé Bocal | Région parisienne (temps partiel)
> > TéléGrenoble | Grenoble - Voiron
> > TL7, Télévision Loire 7 | Saint-Etienne
> > Télévision Locale du Choletais | Cholet - La Roche-sur-Yon - Nantes
> > BFM Lyon Métropole | LyonVillefranche-sur-Saône – Lyon – Vienne
> > TVR | Rennes
> > ViàTélé Paese | Calvi – L’Île RousseCorte
> > TV Tours Val-de-Loire | Tours - Blois
> > TV Vendée
> > TV7 Bordeaux | Bordeaux - Arcacho
> > TV8 Mont-Blanc | Savoie et Haute-Savoie
> > TVPI | Bayonne
> > BFM Var | Toulon - Hyères
> > Museum TV Paris | Région parisienne
> > vià Occitanie Montpellier | Montpellier
> > vià Occitanie Pays catalan | Perpignan
> > vià Occitanie Pays gardois | NîmesAlès
> > vià Occitanie Toulouse | Toulouse
> > Vosges Télévision | Epinal - Vittel
> > Wéo Picardie | Abbeville - Amiens
> > Wéo Nord-Pas de Calais | Lille
> 
> Bonjour, je vous remercie de m'avoir mis la liste des chaîne, j'ajouterai une liste m3u et je la remplirai cette semaine.

merci , c possible mets tous les chaines dans une seule liste

**Comment by LeBazarDeBryan** [comment]
> > > Alsace 20 | StrasbourgMulhouse
> > > Angers télé | Angers
> > > BFM Azur | Nice – Menton - Cannes – Grasse – Saint Raphaël - Mercantour
> > > BDM TV | Région parisienne (temps partiel)
> > > BFM Paris | Île-de-France
> > > Bip TV | Issoudun - Argenton-sur-Creuse
> > > Canal 32 | Troyes
> > > BFM DICI | GapDigne-les-Bains – Serres – SisteronChâteau-Arnoux
> > > Demain ! IDF | Région parisienne (temps partiel)
> > > BFM Grand Lille | Lille (R15)
> > > BFM Grand Littoral | Boulogne-sur-Mer - Dunkerque
> > > IDF1 | Région parisienne
> > > LCN La Chaîne Normande | Rouen - Neufchâtel-en-Bray
> > > LDV TV | Monistrol-sur-Loire
> > > LMty Sarthe | Le Mans
> > > viàMATÉLÉ | Saint-Quentin - Hirson
> > > viàMoselle TV | Metz - Verdun - Forbach - Longwy - Sarrebourg
> > > Télénantes | Nantes
> > > BFM Marseille | Marseille
> > > Tébéo | Brest
> > > Tébésud | Lorient - Vannes
> > > Télé Bocal | Région parisienne (temps partiel)
> > > TéléGrenoble | Grenoble - Voiron
> > > TL7, Télévision Loire 7 | Saint-Etienne
> > > Télévision Locale du Choletais | Cholet - La Roche-sur-Yon - Nantes
> > > BFM Lyon Métropole | LyonVillefranche-sur-Saône – Lyon – Vienne
> > > TVR | Rennes
> > > ViàTélé Paese | Calvi – L’Île RousseCorte
> > > TV Tours Val-de-Loire | Tours - Blois
> > > TV Vendée
> > > TV7 Bordeaux | Bordeaux - Arcacho
> > > TV8 Mont-Blanc | Savoie et Haute-Savoie
> > > TVPI | Bayonne
> > > BFM Var | Toulon - Hyères
> > > Museum TV Paris | Région parisienne
> > > vià Occitanie Montpellier | Montpellier
> > > vià Occitanie Pays catalan | Perpignan
> > > vià Occitanie Pays gardois | NîmesAlès
> > > vià Occitanie Toulouse | Toulouse
> > > Vosges Télévision | Epinal - Vittel
> > > Wéo Picardie | Abbeville - Amiens
> > > Wéo Nord-Pas de Calais | Lille
> > 
> > Bonjour, je vous remercie de m'avoir mis la liste des chaîne, j'ajouterai une liste m3u et je la remplirai cette semaine.
> 
> merci , c possible mets tous les chaines dans une seule liste 

Oui c'est possible.

**Comment by ARAB-IPTV** [comment]
voici les lien m3u8 des chaines bfm locale 
BFM BUISSNESS : https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_BUSINESS/index.m3u8?start=LIVE&end=END
BFM ALSACE : https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_ALSACE/index.m3u8?start=LIVE&end=END
BFM HAUTE PROVENCE : https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_DICI_HAUTEPROVENCE/index.m3u8?start=LIVE&end=END
BFM LILLE : https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFMGRANDLILLE/index.m3u8?start=LIVE&end=END
BFM LITTORAL: https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFMGRANDLITTORAL/index.m3u8?start=LIVE&end=END
BFM LYON: https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_LYON/index.m3u8?start=LIVE&end=END
BFM MARSEILLE: https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_MARSEILLEPROV/index.m3u8?start=LIVE&end=END
BFM NICE: https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_NICECOTEDAZUR/index.m3u8?start=LIVE&end=END
BFM NORMANDIE: https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_NORMANDIE/index.m3u8?start=LIVE&end=END
BFM PARIS: https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_PARIS/index.m3u8?start=LIVE&end=END
BFM ALPES : https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_DICI_ALPESDUSUD/index.m3u8?start=LIVE&end=END
https://ncdn-live-bfm.pfd.sfr.net/shls/LIVE$BFM_TOULONVAR/index.m3u8?start=LIVE&end=END  : BFM ` TOULON

**Comment by ARAB-IPTV** [comment]
LES CHAINE FRANCOPHONE : 
LES CHAINES BELGE : 
LA UNE - TIPIK - LA TROIS https://auvio.rtbf.be/direct
GROUPE RTL : https://www.rtlplay.be/
club rtl :https://origin2-rtlbe.live.6cloud.fr/pool_z6h2o6qd/clubrtl/rtlbehde/hls_short_enc_clubrtl/NA/vcMgoH5/index.m3u8
plug rtl : https://origin2-rtlbe.live.6cloud.fr/pool_z6h2o6qd/plugrtl/rtlbehde/hls_short_enc_plugrtl/NA/vwY8N2N/index.m3u8
rtl tvi : https://origin2-rtlbe.live.6cloud.fr/pool_z6h2o6qd/rtltvi/rtlbehde/hls_short_enc_rtltvi/NA/vwY8N2N/index.m3u8
LN24 : https://live.digiteka.com/1/bEg0RmFLb1JMYXRI/dGhqbmIw/hls/live/playlist.m3u8
BX1 : https://59959724487e3.streamlock.net/stream/live/chunklist.m3u8
[Canal Zoom( ](http://www.canalzoom.be/live/)
[MA Télé]	https://live.matele.be/hls/live.m3u8
[Notélé] https://streaming01.divercom.be/notele_live/_definst_/direct.stream/chunklist.m3u8
[RTC Télé-Liège] https://www.rtc.be/live
[Télé MB] http://www.telemb.be/direct
[Télésambre] https://www.telesambre.be/direct
[TV Com] https://www.tvcom.be/live
[TV Lux] https://www.tvlux.be/live
[Vedia] https://www.vedia.be/www/live

**Comment by ARAB-IPTV** [comment]
LES CHAINE DU CANADA : 
ICI RDI : https://rcavlive.akamaized.net/hls/live/704025/xcanrdi/master.m3u8
ICI TELE : https://ici.radio-canada.ca/tele
TVA : https://www.qub.ca/tvaplus/tva/en-direct
NOOVOO : https://www.noovo.ca/en-direct
TELE QUEBEC : https://bcovlive-a.akamaihd.net/575d86160eb143458d51f7ab187a4e68/us-east-1/6101674910001/profile_1/chunklist.m3u8

**Comment by ARAB-IPTV** [comment]
MONACO INFO : https://webtvmonacoinfo.mc/live/prod_720/index.m3u8
RTL 1 LUXEMBOURG : https://live-edge.rtl.lu/channel1/smil:channel1/playlist.m3u8

**Comment by ARAB-IPTV** [comment]
les chaines locale suisse : 
one tv : http://edge16.vedge.infomaniak.com/livecast/ik:onefmmd/chunklist.m3u8
lfmtv: https://edge19.vedge.infomaniak.com/livecast/ik:lfmmd/chunklist.m3u8
rouge tv : https://edge15.vedge.infomaniak.com/livecast/rougetv.stream/chunklist.m3u8
tvm3 : https://edge12.vedge.infomaniak.com/livecast/ik:tvm3/chunklist.m3u8
canal9 : https://edge14.vedge.infomaniak.com/livecast/ik:livehd/chunklist.m3u8
canal alpha ne : https://edge14.vedge.infomaniak.com/livecast/ik:canalalpha/chunklist.m3u8
canal alpha ju : https://edge20.vedge.infomaniak.com/livecast/ik:canalalphaju/chunklist.m3u8
lémanbleu : https://naxoo.vedge.infomaniak.com/livecast/ik:naxoo/manifest.m3u8
la télé : https://edge21.vedge.infomaniak.com/livecast/latele2/chunklist.m3u8

**Comment by ARAB-IPTV** [comment]
tnt tv tahiti : https://tntv-samsung-fr.amagi.tv/playlist.m3u8
antenne réunion : https://cache-video-server-04.zeop.tv/bpk-token/agkpugwbabaayf1fppg22gbaaaaaaaaaaaagtbngrrneuzah/live/c3eds/antreunihd/hls_fta/antreunihd.m3u8

**Comment by LeBazarDeBryan** [comment]
Bonjour, j'ai commencé à compléter la liste m3u voici le lien : https://raw.githubusercontent.com/LeBazarDeBryan/XTVZ_/main/IPTV/Liste%20pour%20@hemzaberkane.m3u

Si vous voulez que je change le nom de la liste disait le moi !

**Comment by ARAB-IPTV** [comment]
je veux que toutes les chaine tnt et le autre dans une seule liste " k-net"

**Comment by ARAB-IPTV** [comment]
en peut discutter sur twitter !

**Comment by LeBazarDeBryan** [comment]
> en peut discutter sur twitter !

Si vous voulez
