### ISSUE TITLE
Déconnexion 

### ISSUE THREAD

**Issue by Dxnch** [LeBazarDeBryan/XTVZ_#2]
Bonjour,

j’ai ajouté la liste All.m3u et chaque chaîne se déconnecte au bout d’une minute environ.

**Comment by LeBazarDeBryan** [comment]
Bonjour, Merci d'avoir pris le temps de signalé ce problème. Ceci est normale car les liens IPTV (pas très légale) sont entrain d'être éliminé un par un jusqu'à qu'il n'y est plus un seul lien car ce sont des liens IPTV illégale.

C'est aussi de ma faute car ça fait depuis quelque jour que je n'est pas mis la playlist à jour.
Je l'ai remplacer en espérant que ça ne va pas se déconnecter.

**Comment by Dxnch** [comment]
De rien, les liens fonctionnent dans le sens où je reçois l'image mais finissent par se déconnecter rapidement. En tout cas merci pour votre travail !

**Comment by LeBazarDeBryan** [comment]
De rien, aussi, c'est normal si l'image coupe au bout de 30 secondes ou plus, c'est (peut-être) à causse de la connexion internet, des liens ou peut-être d'autre chose ¯\_(ツ)_/¯
